DROP TABLE IF EXISTS historiqueetatdemande,
visa,
carteresident,
checkdossiersupplementaire,
checkdossierstandard,
demande,
visatransformable,
passport,
demandeur,
etatdemande,
dossiersupplementaire,
dossierstandard,
nationalite,
situationdefamille,
typedemande,
typevisa CASCADE;

DROP SEQUENCE IF EXISTS seq_historiqueetatdemande,
seq_visa,
seq_carteresident,
seq_checkdossiersupplementaire,
seq_checkdossierstandard,
seq_demande,
seq_visatransformable,
seq_passport,
seq_demandeur,
seq_etatdemande,
seq_dossiersupplementaire,
seq_dossierstandard,
seq_nationalite,
seq_situationdefamille,
seq_typedemande,
seq_typevisa;